package properties

const (
	Config                   = "logging.config"
	ConsoleEnabled           = "logging.console.enabled"
	ConsoleCharset           = "logging.charset.console"
	FileCharset              = "logging.charset.file"
	RootLevel                = "logging.level.root"
	LevelPrefix              = "logging.level."
	GroupPrefix              = "logging.group."
	ConsolePattern           = "logging.pattern.console"
	FilePattern              = "logging.pattern.file"
	DateFormatPattern        = "logging.pattern.dateformat"
	LevelPattern             = "logging.pattern.level"
	CorrelationPattern       = "logging.pattern.correlation"
	RollingFileNamePattern   = "logging.pattern.rolling-file-name"
	ExceptionConversionWord  = "logging.exception-conversion-word"
	FileName                 = "logging.file.name"
	FilePath                 = "logging.file.path"
	LegacyFileName           = "logging.file"
	LegacyFilePath           = "logging.path"
	FileCleanHistoryOnStart  = "logging.file.clean-history-on-start"
	FileMaxHistory           = "logging.file.max-history"
	FileMaxSize              = "logging.file.max-size"
	FileTotalSizeCap         = "logging.file.total-size-cap"
	ConsoleThreshold         = "logging.threshold.console"
	FileThreshold            = "logging.threshold.file"
	IncludeApplicationName   = "logging.include-application-name"
	IncludeApplicationGroup  = "logging.include-application-group"
	RegisterShutdownHook     = "logging.register-shutdown-hook"
	StructuredConsoleFormat  = "logging.structured.format.console"
	StructuredFileFormat     = "logging.structured.format.file"
	StructuredJSONInclude    = "logging.structured.json.include"
	StructuredJSONExclude    = "logging.structured.json.exclude"
	StructuredJSONRename     = "logging.structured.json.rename"
	StructuredJSONAdd        = "logging.structured.json.add"
	StructuredContextInclude = "logging.structured.json.context.include"
	StructuredContextPrefix  = "logging.structured.json.context.prefix"
	StacktraceCommonFrames   = "logging.structured.json.stacktrace.include-common-frames"
	StacktraceHashes         = "logging.structured.json.stacktrace.include-hashes"
	StacktraceMaxLength      = "logging.structured.json.stacktrace.max-length"
	StacktraceMaxDepth       = "logging.structured.json.stacktrace.max-throwable-depth"
	StacktracePrinter        = "logging.structured.json.stacktrace.printer"
	StacktraceRoot           = "logging.structured.json.stacktrace.root"
	ECSServiceEnvironment    = "logging.structured.ecs.service.environment"
	ECSServiceName           = "logging.structured.ecs.service.name"
	ECSServiceNodeName       = "logging.structured.ecs.service.node-name"
	ECSServiceVersion        = "logging.structured.ecs.service.version"
	GELFHost                 = "logging.structured.gelf.host"
	GELFServiceVersion       = "logging.structured.gelf.service.version"
	ApplicationName          = "goark.application.name"
	ApplicationGroup         = "goark.application.group"
)

const (
	DefaultDateFormat                    = "yyyy-MM-dd HH:mm:ss.SSS"
	DefaultLevelPattern                  = "%5p"
	DefaultExceptionConversionWord       = "%wEx"
	DefaultMaxFileSize             int64 = 10 * 1000 * 1000
	DefaultMaxHistory                    = 7
)
